[features]
seeds = false
skip-lint = false

[programs.localnet]
degen_launch = "6UBFGLf5YBdVAzdzzoMhQsL3pM1KjgRp7EgVDCP4UqGV"

[programs.devnet]
degen_launch = "6UBFGLf5YBdVAzdzzoMhQsL3pM1KjgRp7EgVDCP4UqGV"

[programs.mainnet]
degen_launch = "6UBFGLf5YBdVAzdzzoMhQsL3pM1KjgRp7EgVDCP4UqGV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
solana_version = "1.17.22"
